# Generated by Django 4.0.3 on 2022-03-31 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrateur', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrateur',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date de création'),
        ),
        migrations.AddField(
            model_name='administrateur',
            name='updated_at',
            field=models.DateTimeField(null=True, verbose_name='Dernièrre modification'),
        ),
        migrations.AlterField(
            model_name='administrateur',
            name='telephone',
            field=models.CharField(max_length=30, null=True, verbose_name='Téléphone'),
        ),
    ]
