# Generated by Django 4.0.3 on 2022-07-25 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrateur', '0002_administrateur_created_at_administrateur_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrateur',
            name='actif',
            field=models.CharField(default='oui', max_length=5, verbose_name='Actif'),
        ),
    ]
