# Generated by Django 4.0.3 on 2022-07-25 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrateur', '0003_administrateur_actif'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrateur',
            name='actif',
        ),
    ]
