# Generated by Django 4.0.3 on 2022-04-01 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agent', '0004_remove_agent_telephone_agent_trigramme'),
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comptable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=100, verbose_name='Nom Complet')),
                ('email_envoi_facture', models.CharField(max_length=80, verbose_name="2mail d'nvoi de facture")),
                ('telephone', models.CharField(max_length=50, verbose_name='Telephone ')),
                ('mobile', models.CharField(max_length=50, verbose_name='Mobile ')),
            ],
            options={
                'verbose_name': 'Reference comptable',
            },
        ),
        migrations.CreateModel(
            name='ServiceGestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=100, verbose_name='Nom Complet')),
                ('email', models.CharField(max_length=100, verbose_name='Emailt')),
                ('telephone', models.CharField(max_length=100, verbose_name='Telephone')),
                ('mobile', models.CharField(max_length=100, verbose_name='Mobilet')),
            ],
            options={
                'verbose_name': 'Reference service gestion',
            },
        ),
        migrations.AddField(
            model_name='client',
            name='code_client',
            field=models.CharField(max_length=50, null=True, verbose_name='Code client'),
        ),
        migrations.AddField(
            model_name='client',
            name='code_postal',
            field=models.CharField(max_length=50, null=True, verbose_name='Code postal'),
        ),
        migrations.AddField(
            model_name='client',
            name='complement_adresse',
            field=models.CharField(max_length=100, null=True, verbose_name="complement d'adresse"),
        ),
        migrations.AddField(
            model_name='client',
            name='email_agence',
            field=models.CharField(max_length=100, null=True, verbose_name='Email Agence'),
        ),
        migrations.AddField(
            model_name='client',
            name='fonction',
            field=models.CharField(default='Vide', max_length=30, verbose_name='Fonction'),
        ),
        migrations.AddField(
            model_name='client',
            name='mobile',
            field=models.CharField(max_length=20, null=True, verbose_name='Societe'),
        ),
        migrations.AddField(
            model_name='client',
            name='ref_societe',
            field=models.CharField(max_length=100, null=True, verbose_name='Référence de la société'),
        ),
        migrations.AddField(
            model_name='client',
            name='siret',
            field=models.CharField(max_length=100, null=True, verbose_name='SIRET'),
        ),
        migrations.AddField(
            model_name='client',
            name='societe',
            field=models.CharField(default='Vide', max_length=100, verbose_name='Societe'),
        ),
        migrations.AddField(
            model_name='client',
            name='telephone_agence',
            field=models.CharField(max_length=50, null=True, verbose_name='Telephone Agence'),
        ),
        migrations.AddField(
            model_name='client',
            name='titre',
            field=models.CharField(default='Mr', max_length=20, verbose_name='Totre'),
        ),
        migrations.AddField(
            model_name='client',
            name='tva_intercommunautaire',
            field=models.CharField(max_length=100, null=True, verbose_name='TVA Intercommunautaire'),
        ),
        migrations.AddField(
            model_name='client',
            name='ville',
            field=models.CharField(default='Vide', max_length=80, verbose_name='Ville'),
        ),
        migrations.AlterField(
            model_name='client',
            name='adresse',
            field=models.CharField(default=' ', max_length=300, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='client',
            name='telephone',
            field=models.CharField(max_length=20, null=True, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='client',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Concession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agence_secteur_rattachement', models.CharField(max_length=100, null=True, verbose_name='Agence du secteur de rattachement')),
                ('nom_concessionnaire', models.CharField(max_length=100, null=True, verbose_name='Nom Complet')),
                ('numero_proposition_prestation', models.CharField(max_length=100, null=True, verbose_name='Numéro de proposition de prestation')),
                ('nom_complet', models.CharField(max_length=100, verbose_name='Nom Complet')),
                ('as_client', models.CharField(max_length=100, null=True, verbose_name='AS client ')),
                ('origine_client', models.CharField(max_length=100, null=True, verbose_name='Origine Client')),
                ('suivie_technique_client', models.CharField(max_length=100, null=True, verbose_name='Nom Complet')),
                ('agent_rattache', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_rattachee', to='agent.agent')),
            ],
            options={
                'verbose_name': 'Information concession',
            },
        ),
        migrations.AddField(
            model_name='client',
            name='info_concession',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='informations_concession', to='client.concession'),
        ),
        migrations.AddField(
            model_name='client',
            name='ref_comptable',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reference_comptable', to='client.comptable'),
        ),
        migrations.AddField(
            model_name='client',
            name='ref_service_gestion',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reference_service_gestion', to='client.servicegestion'),
        ),
    ]
