# Generated by Django 4.0.3 on 2022-04-13 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_alter_client_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=100, null=True, verbose_name='Nom complet')),
                ('emal', models.CharField(max_length=100, null=True, verbose_name='Email')),
                ('telephone', models.CharField(max_length=100, null=True, verbose_name='Telephone')),
                ('mobile', models.CharField(max_length=100, null=True, verbose_name='Mobile')),
                ('fonction', models.CharField(max_length=100, verbose_name='Fonction')),
            ],
            options={
                'verbose_name': 'Information Passeur',
            },
        ),
        migrations.AddField(
            model_name='client',
            name='passeur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='passeurs_client', to='client.passeur'),
        ),
    ]
