# Generated by Django 4.0.3 on 2022-04-21 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_passeur_client_passeur'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='statut',
            field=models.IntegerField(max_length=50, null=True, verbose_name='statut du client'),
        ),
    ]
