# Generated by Django 4.0.3 on 2022-07-25 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_alter_client_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='actif',
            field=models.CharField(default='oui', max_length=5, verbose_name='Actif'),
        ),
    ]
