# Generated by Django 4.1.1 on 2022-09-14 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salarie', '0004_remove_salarie_actif'),
        ('client', '0008_remove_client_actif'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='salarie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salarie_client_pro', to='salarie.salarie'),
        ),
        migrations.AddField(
            model_name='client',
            name='type',
            field=models.CharField(default='particulier', max_length=50, verbose_name='type de client'),
        ),
    ]
