# Generated by Django 4.1.1 on 2022-09-14 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_client_salarie_client_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='type',
        ),
    ]
