# Generated by Django 4.1.1 on 2022-09-20 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0010_remove_client_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='passeur',
        ),
        migrations.RemoveField(
            model_name='client',
            name='salarie',
        ),
        migrations.AddField(
            model_name='client',
            name='type',
            field=models.CharField(default='particulier', max_length=30, verbose_name='Type de client'),
        ),
    ]
