# Generated by Django 4.1.1 on 2022-09-20 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0011_remove_client_passeur_remove_client_salarie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='adresse',
            field=models.CharField(default=' ', max_length=300, null=True, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='client',
            name='fonction',
            field=models.CharField(default='Vide', max_length=30, null=True, verbose_name='Fonction'),
        ),
        migrations.AlterField(
            model_name='client',
            name='societe',
            field=models.CharField(default='Vide', max_length=100, null=True, verbose_name='Societe'),
        ),
        migrations.AlterField(
            model_name='client',
            name='titre',
            field=models.CharField(default='Mr', max_length=20, null=True, verbose_name='Totre'),
        ),
    ]
