# Generated by Django 4.1.1 on 2022-09-25 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0013_client_created_at_client_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='ville',
            field=models.CharField(default='Vide', max_length=80, null=True, verbose_name='Ville'),
        ),
    ]
