# Generated by Django 4.0.3 on 2022-03-31 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0004_remove_agent_telephone_agent_trigramme'),
        ('salarie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarie',
            name='agent_rattache',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_rattache', to='agent.agent'),
        ),
        migrations.AddField(
            model_name='salarie',
            name='fonction',
            field=models.CharField(default='', max_length=300, verbose_name='Fonction'),
        ),
        migrations.AddField(
            model_name='salarie',
            name='mobile',
            field=models.CharField(max_length=20, null=True, verbose_name='Mobile'),
        ),
        migrations.AddField(
            model_name='salarie',
            name='titre',
            field=models.CharField(default='', max_length=300, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='salarie',
            name='telephone',
            field=models.CharField(max_length=20, null=True, verbose_name='Téléphone'),
        ),
    ]
