# Generated by Django 4.0.3 on 2022-03-31 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='created_at',
            field=models.DateTimeField(null=True, verbose_name='date de création'),
        ),
        migrations.AddField(
            model_name='agent',
            name='uodated_at',
            field=models.DateTimeField(null=True, verbose_name='date dernière modification'),
        ),
    ]
