# Generated by Django 4.1.1 on 2022-09-25 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salarie', '0005_salarie_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarie',
            name='code',
            field=models.CharField(max_length=50, null=True, verbose_name='code'),
        ),
        migrations.AddField(
            model_name='salarie',
            name='company',
            field=models.CharField(max_length=50, null=True, verbose_name='companie'),
        ),
        migrations.AddField(
            model_name='salarie',
            name='created_at',
            field=models.DateTimeField(null=True, verbose_name='Date création'),
        ),
        migrations.AddField(
            model_name='salarie',
            name='updated_at',
            field=models.DateTimeField(null=True, verbose_name='Date modification'),
        ),
    ]
