# Generated by Django 4.0.3 on 2022-03-31 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_agent_created_at_agent_uodated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='uodated_at',
            new_name='updated_at',
        ),
    ]
