# Generated by Django 4.0.3 on 2022-03-31 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0003_rename_uodated_at_agent_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='telephone',
        ),
        migrations.AddField(
            model_name='agent',
            name='trigramme',
            field=models.CharField(max_length=40, null=True, verbose_name='trigramme'),
        ),
    ]
