# Generated by Django 4.1.1 on 2022-09-14 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0007_agent_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='type',
        ),
    ]
